### ISSUE TITLE
bug: startDate not correct

### ISSUE THREAD

**Issue by matteokjh** [kevinsqi/react-calendar-heatmap#132]
[Code Sandbox](https://codesandbox.io/s/react-calendar-heatmap-basic-demo-ls2j6?file=/src/index.js)

as you can see, `startDate={"2020-01-01"}` but it seems to start from '2020-01-02'

**Comment by ZeyadKhattab** [comment]
yes, #128 should fix it

**Comment by matteokjh** [comment]
> yes, #128 should fix it

thx
